import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { access, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import test from "node:test";
import { ISSUE_174_DEMONSTRATED_PATHS } from "./issue-174-evidence-source.mjs";
import {
  assertIssue174EvidenceSanitized,
  inspectIssue174RetainedRunState,
  ISSUE_174_SCENARIO,
  validateIssue174RealEvidence,
} from "./issue-174-real-evidence.mjs";

const execFileAsync = promisify(execFile);
const repositoryRoot = fileURLToPath(new URL("..", import.meta.url));
const manifestPath = fileURLToPath(new URL(
  "../acceptance/issue-174.manifest.json",
  import.meta.url,
));
const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
const evidenceUrl = new URL("../acceptance/evidence/issue-174.real.json", import.meta.url);
const evidenceExists = await access(evidenceUrl).then(() => true, () => false);

test("issue 174 manifest binds the one gated real-provider Project-commit proof", () => {
  assert.equal(manifest.schemaVersion, 1);
  assert.equal(manifest.issue, 174);
  assert.equal(manifest.parentPrd, 169);
  assert.equal(manifest.sourceSpecification.issue, 168);
  assert.equal(manifest.scenario.id, ISSUE_174_SCENARIO);
  assert.equal(manifest.scenario.provider.kind, "openai-codex");
  assert.equal(manifest.scenario.provider.simulationAllowed, false);
  assert.equal(manifest.scenario.requiredOutcome.exactlyOneTerminalEnvelope, true);
  assert.equal(manifest.scenario.requiredOutcome.exactlyOneChildCommit, true);
  assert.equal(manifest.environmentGate.name, "SANDKING_REAL_SANDCASTLE_ACCEPTANCE");
  assert.equal(manifest.environmentGate.fixtureSubstitutionAllowed, false);
  assert.equal(manifest.environmentGate.productionEvidence, false);
  assert.match(manifest.environmentGate.command, /acceptance:issue-174:real/);
  assert.match(JSON.stringify(manifest.verification.commands),
    /test\/real-sandcastle-worker\.test\.mjs/);
  assert.deepEqual(manifest.retainedEvidence.excludes, [
    "credentials and provider account metadata",
    "provider transcripts and unrestricted logs",
    "environment dumps",
    "bootstrap URLs, browser sessions, cookies, and reusable session material",
    "machine-specific Project, state, install, or credential paths",
    "full skill contents",
  ]);
});

test("issue 174 real-provider runner fails closed without invoking a model", async () => {
  await assert.rejects(execFileAsync(process.execPath, [
    fileURLToPath(new URL("./run-issue-174-real-sandcastle.mjs", import.meta.url)),
    manifestPath,
  ], {
    cwd: repositoryRoot,
    env: { PATH: process.env.PATH, LANG: "C.UTF-8" },
    maxBuffer: 1024 * 1024,
  }), (error) => {
    const qualification = JSON.parse(error.stderr.trim().split("\n")[0]);
    assert.deepEqual(qualification.qualification, {
      status: "not-run",
      code: "real_provider_gate_disabled",
      productionEvidence: false,
      fixtureSubstitution: false,
      modelInvoked: false,
    });
    return true;
  });
});

test("issue 174 evidence sanitizer rejects machine paths and full skill material", () => {
  assert.throws(() => assertIssue174EvidenceSanitized({
    evidence: { observation: "/tmp/private-project" },
    prohibitedValues: ["/tmp/private-project"],
  }), /issue_174_real_evidence_not_sanitized/);
  assert.throws(() => assertIssue174EvidenceSanitized({
    evidence: { skillContent: "complete private prompt" },
  }), /issue_174_evidence_prohibited_field/);
});

test("issue 174 runner recognizes a rejected launch before any model invocation", () => {
  assert.deepEqual(inspectIssue174RetainedRunState({
    runs: [],
    launchOutcomes: [{
      response: {
        type: "harness.run.launch.failure",
        code: "harness_worker_provider_unavailable",
        prohibitedSideEffects: {
          harnessRunCreated: false,
          adapterStarted: false,
          projectWrite: false,
        },
      },
    }],
  }), {
    status: "launch-failed",
    code: "harness_worker_provider_unavailable",
    modelInvocationMayHaveOccurred: false,
  });
});

test("retained issue 174 evidence proves the unchanged packaged real delegation", {
  skip: evidenceExists ? false : "generated by the one gated real-provider run",
}, async () => {
  const evidenceText = await readFile(evidenceUrl, "utf8");
  const evidence = validateIssue174RealEvidence(JSON.parse(evidenceText));
  assertIssue174EvidenceSanitized({ evidence });
  await execFileAsync("git", [
    "merge-base", "--is-ancestor", evidence.generatedFromCommit, "HEAD",
  ], { cwd: repositoryRoot });
  const { stdout: changes } = await execFileAsync("git", [
    "diff", "--name-only", `${evidence.generatedFromCommit}..HEAD`, "--",
    ...ISSUE_174_DEMONSTRATED_PATHS,
  ], { cwd: repositoryRoot });
  assert.equal(changes.trim(), "", `issue 174 evidence predates changes:\n${changes}`);
  assert.equal(evidence.adapter.sourcePath,
    "src/production-sandcastle-adapter/sandcastle-v3.mjs");
  assert.equal(evidence.harness.sandKingSeed.revision,
    "bbdc73f3cb2b3cd265330f811306098ffdcc51be");
  assert.equal(evidence.harness.upstream.repository,
    "https://github.com/mattpocock/sandcastle.git");
  assert.equal(evidence.harness.upstream.revision,
    "e99f832f26dc9d245c019a9ddd19fa5dee792427");
  assert.equal(evidence.structuredOutcome.commit, evidence.project.afterCommit);
  assert.ok(Object.values(evidence.project.invariants).every(Boolean));
  assert.equal(evidence.auditReferences.filter(({ action }) =>
    action === "harness.adapter.start").length, 1);
  assert.doesNotMatch(evidenceText,
    /(?:sk-[A-Za-z0-9_-]{12,}|gh[opsu]_[A-Za-z0-9]{12,}|bootstrap\?token=|sandking_session=)/i);
});
