import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { access, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import test from "node:test";
import { ISSUE_174_DEMONSTRATED_PATHS } from "./issue-174-evidence-source.mjs";
import {
  assertIssue174EvidenceSanitized,
  inspectIssue174RetainedRunState,
  ISSUE_174_SCENARIO,
  validateIssue174RealEvidence,
} from "./issue-174-real-evidence.mjs";

const execFileAsync = promisify(execFile);
const repositoryRoot = fileURLToPath(new URL("..", import.meta.url));
const manifestPath = fileURLToPath(new URL(
  "../acceptance/issue-174.manifest.json",
  import.meta.url,
));
const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
const evidenceUrl = new URL("../acceptance/evidence/issue-174.real.json", import.meta.url);
const evidenceExists = await access(evidenceUrl).then(() => true, () => false);
const postProofUrl = new URL(
  "../acceptance/evidence/issue-174.post-proof.json",
  import.meta.url,
);
const postProof = JSON.parse(await readFile(postProofUrl, "utf8"));
const sha256 = (value) => `sha256:${createHash("sha256").update(value).digest("hex")}`;

test("issue 174 manifest binds the one gated real-provider Project-commit proof", () => {
  assert.equal(manifest.schemaVersion, 1);
  assert.equal(manifest.issue, 174);
  assert.equal(manifest.parentPrd, 169);
  assert.equal(manifest.sourceSpecification.issue, 168);
  assert.equal(manifest.scenario.id, ISSUE_174_SCENARIO);
  assert.equal(manifest.scenario.provider.kind, "openai-codex");
  assert.equal(manifest.scenario.provider.simulationAllowed, false);
  assert.deepEqual(manifest.scenario.provider.sandbox, {
    provider: "docker",
    image: "sandcastle:sandking-real-worker",
    configurationSource: ".sandcastle/Dockerfile",
  });
  assert.equal(manifest.scenario.requiredOutcome.exactlyOneTerminalEnvelope, true);
  assert.equal(manifest.scenario.requiredOutcome.exactlyOneChildCommit, true);
  assert.equal(manifest.environmentGate.name, "SANDKING_REAL_SANDCASTLE_ACCEPTANCE");
  assert.equal(manifest.environmentGate.fixtureSubstitutionAllowed, false);
  assert.equal(manifest.environmentGate.productionEvidence, false);
  assert.match(manifest.environmentGate.command, /acceptance:issue-174:real/);
  assert.match(JSON.stringify(manifest.verification.commands),
    /test\/real-sandcastle-worker\.test\.mjs/);
  assert.deepEqual(manifest.retainedEvidence.excludes, [
    "credentials and provider account metadata",
    "provider transcripts and unrestricted logs",
    "environment dumps",
    "bootstrap URLs, browser sessions, cookies, and reusable session material",
    "machine-specific Project, state, install, or credential paths",
    "full skill contents",
  ]);
});

test("issue 174 real-provider runner fails closed without invoking a model", async () => {
  await assert.rejects(execFileAsync(process.execPath, [
    fileURLToPath(new URL("./run-issue-174-real-sandcastle.mjs", import.meta.url)),
    manifestPath,
  ], {
    cwd: repositoryRoot,
    env: { PATH: process.env.PATH, LANG: "C.UTF-8" },
    maxBuffer: 1024 * 1024,
  }), (error) => {
    const qualification = JSON.parse(error.stderr.trim().split("\n")[0]);
    assert.deepEqual(qualification.qualification, {
      status: "not-run",
      code: "real_provider_gate_disabled",
      productionEvidence: false,
      fixtureSubstitution: false,
      modelInvoked: false,
    });
    return true;
  });
});

test("issue 174 evidence sanitizer rejects machine paths and full skill material", () => {
  assert.throws(() => assertIssue174EvidenceSanitized({
    evidence: { observation: "/tmp/private-project" },
    prohibitedValues: ["/tmp/private-project"],
  }), /issue_174_real_evidence_not_sanitized/);
  assert.throws(() => assertIssue174EvidenceSanitized({
    evidence: { skillContent: "complete private prompt" },
  }), /issue_174_evidence_prohibited_field/);
});

test("issue 174 runner recognizes a rejected launch before any model invocation", () => {
  assert.deepEqual(inspectIssue174RetainedRunState({
    runs: [],
    launchOutcomes: [{
      response: {
        type: "harness.run.launch.failure",
        code: "harness_worker_provider_unavailable",
        prohibitedSideEffects: {
          harnessRunCreated: false,
          adapterStarted: false,
          projectWrite: false,
        },
      },
    }],
  }), {
    status: "launch-failed",
    code: "harness_worker_provider_unavailable",
    modelInvocationMayHaveOccurred: false,
  });
});

test("retained issue 174 evidence proves the unchanged packaged real delegation", {
  skip: evidenceExists ? false : "generated by the one gated real-provider run",
}, async () => {
  const evidenceText = await readFile(evidenceUrl, "utf8");
  const evidence = validateIssue174RealEvidence(JSON.parse(evidenceText));
  assertIssue174EvidenceSanitized({ evidence });
  assert.equal(postProof.schemaVersion, 1);
  assert.equal(postProof.issue, 174);
  assert.equal(postProof.kind, "post-proof-package-boundary");
  assert.equal(postProof.realEvidenceGeneratedFromCommit, evidence.generatedFromCommit);
  assert.deepEqual(postProof.allowedChangedFiles.map(({ path }) => path), [
    "package.json",
    "src/production-sandcastle-adapter/.npmignore",
    "test/issue-174-acceptance-evidence.test.mjs",
    "test/issue-174-package-boundary.test.mjs",
    "test/issue-175-acceptance-evidence.test.mjs",
    "test/issue-175-evidence-source.mjs",
    "test/issue-175-source-verification.mjs",
    "test/run-issue-175-acceptance.mjs",
  ]);
  for (const file of postProof.allowedChangedFiles) {
    assert.match(file.integrity, /^sha256:[a-f0-9]{64}$/);
    assert.equal(
      sha256(await readFile(new URL(`../${file.path}`, import.meta.url))),
      file.integrity,
      `${file.path} differs from the bounded post-proof package refinement`,
    );
  }
  await execFileAsync("git", [
    "merge-base", "--is-ancestor", evidence.generatedFromCommit, "HEAD",
  ], { cwd: repositoryRoot });
  const { stdout: changes } = await execFileAsync("git", [
    "diff", "--name-only", `${evidence.generatedFromCommit}..HEAD`, "--",
    ...ISSUE_174_DEMONSTRATED_PATHS,
  ], { cwd: repositoryRoot });
  const allowedChanges = new Set(postProof.allowedChangedFiles.map(({ path }) => path));
  const changedPaths = changes.trim().split("\n").filter(Boolean);
  assert.deepEqual(
    changedPaths.filter((path) => !allowedChanges.has(path)),
    [],
    `issue 174 evidence predates material changes:\n${changes}`,
  );
  const { stdout: status } = await execFileAsync("git", [
    "status", "--short", "--untracked-files=all", "--",
    ...postProof.allowedChangedFiles.map(({ path }) => path),
  ], { cwd: repositoryRoot });
  if (!status.trim()) {
    assert.deepEqual(changedPaths.sort(), [...allowedChanges].sort());
  }
  for (const path of [
    "src/production-sandcastle-adapter/real-worker-v2.mjs",
    "src/production-sandcastle-adapter/sandcastle-v4.mjs",
    "test/run-issue-174-real-sandcastle.mjs",
  ]) {
    const [{ stdout: evidencedSource }, currentSource] = await Promise.all([
      execFileAsync("git", ["show", `${evidence.generatedFromCommit}:${path}`], {
        cwd: repositoryRoot,
        maxBuffer: 1024 * 1024,
      }),
      readFile(new URL(`../${path}`, import.meta.url), "utf8"),
    ]);
    assert.equal(currentSource, evidencedSource, `${path} changed after the real proof`);
  }
  assert.equal(evidence.adapter.sourcePath,
    "src/production-sandcastle-adapter/sandcastle-v4.mjs");
  assert.equal(evidence.harness.sandKingSeed.revision,
    "4357a746267956b431ebfb5e465dcbdbb3b3ec00");
  assert.equal(evidence.harness.upstream.repository,
    "https://github.com/mattpocock/sandcastle.git");
  assert.equal(evidence.harness.upstream.revision,
    "e99f832f26dc9d245c019a9ddd19fa5dee792427");
  assert.equal(evidence.structuredOutcome.commit, evidence.project.afterCommit);
  assert.ok(Object.values(evidence.project.invariants).every(Boolean));
  assert.equal(evidence.auditReferences.filter(({ action }) =>
    action === "harness.adapter.start").length, 1);
  assert.doesNotMatch(evidenceText,
    /(?:sk-[A-Za-z0-9_-]{12,}|gh[opsu]_[A-Za-z0-9]{12,}|bootstrap\?token=|sandking_session=)/i);
});
